# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.SmallIntegerField(default=None),
        ),
    ]
