# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('picture', models.ImageField(upload_to='events')),
                ('picture_width', models.SmallIntegerField()),
                ('picture_height', models.SmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('place', models.TextField(max_length=300)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('lat_position', models.DecimalField(decimal_places=8, max_digits=10)),
                ('long_position', models.DecimalField(decimal_places=8, max_digits=10)),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('status', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oganizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.Organizer')),
            ],
        ),
    ]
