# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('picture', models.ImageField(upload_to='paintings')),
                ('picture_width', models.SmallIntegerField()),
                ('picture_height', models.SmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('materials', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('price_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR')], default='USD', max_length=3)),
                ('size_width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size_height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size_unit', models.CharField(choices=[('IN', 'IN'), ('CM', 'CM')], default='IN', max_length=2)),
                ('quantity', models.IntegerField()),
                ('admin_message', models.TextField(max_length=1000)),
                ('views', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('featured_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='painting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.Paintings'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
